export * from './AnmeldungApi';
import { AnmeldungApi } from './AnmeldungApi';
export * from './DefaultApi';
import { DefaultApi } from './DefaultApi';
export * from './DisziplinApi';
import { DisziplinApi } from './DisziplinApi';
export * from './ErgebnisApi';
import { ErgebnisApi } from './ErgebnisApi';
export * from './MetaApi';
import { MetaApi } from './MetaApi';
export * from './NutzerApi';
import { NutzerApi } from './NutzerApi';
export * from './TeilnehmerApi';
import { TeilnehmerApi } from './TeilnehmerApi';
export const APIS = [AnmeldungApi, DefaultApi, DisziplinApi, ErgebnisApi, MetaApi, NutzerApi, TeilnehmerApi];
