/**
 * Sportfest Backend
 * Sportfest backend
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Disziplin {
    id?: number;

    bezeichnung?: string;

    beschreibung?: string;

    team?: boolean;

    variablen?: Array<models.Variable>;

    regeln?: Array<models.Regeln>;

}
