/**
 * Sportfest Backend
 * Sportfest backend
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Ergebnis {
    id?: number;

    punkte?: number;

    ergebnisse?: Array<models.Ergebnis>;

    klasse?: models.Klasse;

    schueler?: models.Schueler;

    disziplin?: models.Disziplin;

}
