/**
 * Sportfest Backend
 * Sportfest backend
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Typ {
    id?: number;

    datentyp?: Typ.DatentypEnum;

    einheit?: string;

    /**
     * RegEx
     */
    format?: string;

    /**
     * Beispiel
     */
    bsp?: string;

}
export namespace Typ {
    export enum DatentypEnum {
        String = <any> 'string',
        Int = <any> 'int',
        Float = <any> 'float',
        Long = <any> 'long',
        Double = <any> 'double'
    }
}
